#!/bin/bash
options=(
  style=round
  width=6.0
  hidpi=off
  active_color="gradient(top_left=0xff0066ff,bottom_right=0xff00ffcc)"
  # inactive_color=0xff414550
  inactive_color="gradient(top_left=0xff2a3a4a,bottom_right=0xff1a2a3a)"
  blacklist="Safari,ghostty"
)
borders "${options[@]}"
