# Background
background #0d0d0d
background_opacity 0.7
background_blur 40
window_border_width 2pt
active_border_color #7aa2f7
# Font
font_family JetBrainsMono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 19.0

# macOS specific
macos_option_as_alt no
hide_window_decorations titlebar-only
macos_quit_when_last_window_closed yes

# Cursor
cursor_shape underline
cursor #fea639
cursor_blink_interval 0

# Shell
shell zsh
shell_integration enabled

# Selection/Copy
copy_on_select clipboard

# Terminal type
term xterm-256color

# Window
window_padding_width 5

# Tab bar
tab_bar_edge top
tab_bar_style powerline

# Scrollback
scrollback_lines 100000

# Mouse
mouse_hide_wait 3.0
url_color #0087bd
url_style curly
detect_urls yes

# Bell
enable_audio_bell no
visual_bell_duration 0.0

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Keybindings
map ctrl+shift+a load_config_file
map Alt+Tab send_text all \x1b\r

# Colors
foreground #c0caf5
selection_background #33467c
selection_foreground #c0caf5

color0 #15161e
color8 #414868
color1 #f7768e
color9 #f7768e
color2 #9ece6a
color10 #9ece6a
color3 #e0af68
color11 #e0af68
color4 #7aa2f7
color12 #7aa2f7
color5 #bb9af7
color13 #bb9af7
color6 #7dcfff
color14 #7dcfff
color7 #a9b1d6
color15 #c0caf5

confirm_os_window_close 0
# map opt+cmd+space send_text all \x00
