[google-drive]
type = drive
client_id = 655127480999-374soq63b3bs52l9oue7d8bophm600jl.apps.googleusercontent.com
scope = drive
client_secret = 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
copy_shortcut_content = true
description = google-drive to Nextcloud
token = {"access_token":"ya29.a0Aa7pCA-KbP6ymBisHpqs-enH-7G3tk957eFfW60TmKJFeSCHMbF8PRfhKJGTCd8yyzIrDG2z07q5xKHj4CFkhrexcqgyWuX6rqPER_LPmGTWRSUu57LtYIV1trReZI6uzsfk1S6ZwGOqti0YTM6LcqQC7J3PNMQ0Gm-W_DUkpj4j-VnXU8gARcrqjUeDoRDI_YrhQJMaCgYKASgSARYSFQHGX2MiZ6uYfMosJ7VPR9_MMRihoA0206","token_type":"Bearer","refresh_token":"1//06VB3sLpeyA87CgYIARAAGAYSNwF-L9IryplU2GKbNQUh7cCJt50RmI4QzVomEcBX0DNzo6VqAzi1YsrnTb3PdugLJvW9bCDr0gE","expiry":"2025-12-11T21:20:11.713866-08:00","expires_in":3599}
team_drive = 

[nextcloud]
type = webdav
url = https://cloud.vibhoresagar.dev/remote.php/dav/files/vib1240n/
vendor = nextcloud
user = vib1240n
pass = 1cDmY07STFeBT4dvra_7sdVCWUaCZd-_OjEtDiAq5A

