require("items.apple")
require("items.front_app")
require("items.spaces-aerospace")
require("items.menus")
require("items.calendar")
require("items.widgets.battery")
require("items.media")
-- require("items.widgets.cpu")
-- require("items.widgets.memory")
-- require("items.widgets.sensors")
-- require("items.widgets.wifi")

require("items.widgets.combined")
require("items.mode")
