return {
    ["battery_0"] = "\u{ea01}",
    ["battery_10"] = "\u{ea02}",
    ["battery_20"] = "\u{ea04}",
    ["battery_30"] = "\u{ea05}",
    ["battery_40"] = "\u{ea06}",
    ["battery_50"] = "\u{ea07}",
    ["battery_60"] = "\u{ea08}",
    ["battery_70"] = "\u{ea09}",
    ["battery_80"] = "\u{ea0a}",
    ["battery_90"] = "\u{ea0b}",
    ["battery_100"] = "\u{ea03}",
    ["battery_charging_0"] = "\u{ea0c}",
    ["battery_charging_10"] = "\u{ea0d}",
    ["battery_charging_20"] = "\u{ea0f}",
    ["battery_charging_30"] = "\u{ea10}",
    ["battery_charging_40"] = "\u{ea11}",
    ["battery_charging_50"] = "\u{ea12}",
    ["battery_charging_60"] = "\u{ea13}",
    ["battery_charging_70"] = "\u{ea14}",
    ["battery_charging_80"] = "\u{ea15}",
    ["battery_charging_90"] = "\u{ea16}",
    ["battery_charging_100"] = "\u{ea0e}",
    ["battery_charging_slow"] = "\u{ea17}",
    ["battery_warning"] = "\u{ea18}"
}
