# ZSH export and plugins for oh my zsh;
# zmodload zsh/zprof  # Only enable for profiling

# Fix backspace key for SSH sessions
bindkey '^?' backward-delete-char
bindkey '^H' backward-delete-char

# Optimized completion loading - only once per day
autoload -Uz compinit
if [[ -n ~/.zcompdump(#qNmh+24) ]]; then
  compinit -C  # Skip security check for speed
else
  compinit
fi
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
# Speed up completions
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
export ZSH="$HOME/.oh-my-zsh"
eval $(/opt/homebrew/bin/brew shellenv)
zstyle ':omz:plugins:nvm' lazy yes
plugins=(git macos nvm)
# neofetch

# Commented out for faster startup
# clear;fastfetch -c ~/.config/fastfetch/left.jsonc -l none; print -n "\e[H"; fastfetch -c ~/.config/fastfetch/right.jsonc -l none
source $HOME/.config/functions/alias
# source $HOME/.config/functions/stl-step-convert.py
source /opt/homebrew/opt/chruby/share/chruby/auto.sh
source $ZSH/oh-my-zsh.sh
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.config/functions/functions.sh
# c;fastfetch
# source /Users/vib1240n/Development/git-sync/git-sync
# source /Users/vib1240n/Development/git-sync/contrib/git-sync-on-inotify
 # for f in ~/Development/git-sync/*; do source $f; done
# # homebrew exports for formulas
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"
export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk@11/include"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk@17/include"
# PYENV CONFIG
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(oh-my-posh init zsh --config '/opt/homebrew/opt/oh-my-posh/themes/peru.omp.json')"
# EXPORTS
export ANDROID_SDK_ROOT="/opt/homebrew/share/android-commandlinetools"
export PATH="/opt/homebrew/bin/pandoc:$PATH"
export PATH="/opt/homebrew/opt/bison/bin:$PATH"
export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
PRELINE="\r\033[A"

export PATH="/opt/homebrew/opt/mysql-client@8.0/bin:$PATH"
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
export PATH="$PATH:/Applications/WezTerm.app/Contents/MacOS"
export PATH="/opt/homebrew/opt/whois/bin:$PATH"
export PATH="/opt/homebrew/opt/openjdk@21/bin:$PATH"
# Function to sleep MacBook with optional delay in seconds
# clear;fastfetch -c ~/.config/fastfetch/left.jsonc -l none; print -n "\e[H"; fastfetch -c ~/.config/fastfetch/right.jsonc -l none
#
# Add Homebrew completions to FPATH
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
fi

export CONFIG=$HOME/.config
export DEV=$HOME/Development
# zprof
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_BAT=1
# export DEV="/Users/vib1240n/Development/"
export PATH="$HOME/.jenv/bin:$PATH"
export PATH="$HOME/.jenv/bin:$PATH"
if which jenv > /dev/null; then 
  eval "$(jenv init -)"
fi
# jenv() {
#   unset -f jenv
#   export PATH="$HOME/.jenv/bin:$PATH"
#   eval "$(jenv init -)"
#   jenv "$@"
# }
# if which jenv > /dev/null; then eval "$(jenv init -)"; fi
# zprof | head -40  # Commented out - only enable for debugging
clear
export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# pnpm
export PNPM_HOME="/Users/vib1240n/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Created by `pipx` on 2025-11-14 00:18:25
export PATH="$PATH:/Users/vib1240n/.local/bin"
bindkey '	' autosuggest-accept

# Added by Antigravity
export PATH="/Users/vib1240n/.antigravity/antigravity/bin:$PATH"
