#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# yabai -m config mouse_follows_focus on # focus follows mouse
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_modifier alt # mouse modifier
yabai -m config mouse_action1 move # mouse action 1
yabai -m config mouse_action2 resize # mouse action 2

yabai -m config focus_follows_mouse autofocus

echo "loaded mouse support config"
exit 0
